name: Advent Of Code 2019

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    - name: Lint with flake8
      run: flake8 . --ignore="E226,E24,W6,E731" --show-source --statistics
    - name: Test with pytest
      run: pytest
